### ISSUE TITLE
How can this work with latest version of Aurelia

### ISSUE THREAD

**Issue by weoreference** [zewa666/aurelia-node#9]
Hello,

I am trying to use this with the newest release of Aurelia skeleton (0.18.1 as of now), but doing so breaks my dependencies.

What steps can I take to update this codebase so it may work with the latest version of Aurelia and all its dependencies?

Thanks : )
Andy

**Comment by zewa666** [comment]
I'm not sure whats not working. Just downloaded and followed the install instructions and everything works with the new version (0.18.1) being installed. Can you tell me what error is thrown?

**Comment by human-divanshu** [comment]
Can you give me version number of node, npm and jspm that you are using ? I was also getting some errors while setting it up. In a few minutes, I will paste the errors also.

**Comment by human-divanshu** [comment]
Here is the output when I run gulp watch

```
[12:54:23] Using gulpfile ~/node/fic-chat/test/aurelia-node-master/gulpfile.js
[12:54:23] Starting 'nodemon'...
[12:54:23] Starting 'build'...
[12:54:23] Starting 'clean'...
[gulp] [nodemon] 1.7.1
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: *.*
[gulp] [nodemon] starting `node app.js`
[12:54:23] Finished 'nodemon' after 59 ms
[12:54:23] Finished 'clean' after 93 ms
[12:54:23] Starting 'build-system'...
[12:54:23] Starting 'build-html'...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at Function.app.listen (/home/silverflash/node/fic-chat/test/aurelia-node-master/node_modules/express/lib/application.js:556:24)
    at Object.<anonymous> (/home/silverflash/node/fic-chat/test/aurelia-node-master/app.js:35:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[gulp] [nodemon] app crashed - waiting for file changes before starting...
[12:54:24] Finished 'build-html' after 802 ms
[12:54:24] Finished 'build-system' after 817 ms
[12:54:24] Finished 'build' after 914 ms
[12:54:24] Starting 'browser-sync'...
[12:54:24] Finished 'browser-sync' after 41 ms
[12:54:24] Starting 'watch'...
[12:54:24] Finished 'watch' after 20 ms
[BS] Proxying: http://localhost:9000
[BS] Now you can access your site through the following addresses:
[BS] Local URL: http://localhost:7000
[BS] External URL: http://192.168.1.5:7000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```

**Comment by zewa666** [comment]
Node: v0.12.0
Npm: 3.2.1
Jspm: 0.16.11

Ok the error sounds like either the 9000 or 7000 port is already in use when you start up your application. Maybe you have something else running on the same ports? Try editing those ports to something else in the above linked places to lets say 9002 and 7002

**Comment by human-divanshu** [comment]
I am using Cloud9 as my IDE. I have changed 9000 to process.env.PORT in server.js file. So, I think I will need to make some changes for front end to work. Right ?

**Comment by zewa666** [comment]
oh ok sry I've mixed this issue up with the other one.

In order to change the backend port go here: [app.js](https://github.com/zewa666/aurelia-node/blob/master/app.js#L33)
and for the frontend proxy/port: [gulpfile.js](https://github.com/zewa666/aurelia-node/blob/master/gulpfile.js#L107-L111)

**Comment by human-divanshu** [comment]
Thanks a lot man. I was struggling through this since last night.

**Comment by zewa666** [comment]
@human-divanshu glad I was able to help
@weoreference whats the error you get?
